# Tokenize LibriTTS-R Mimi for target LM

For our dataset, we currently simply use the Fish Speech TTS format:
- Text-only data formatted using [ChatML](https://gist.github.com/edwardzjl/8df07c1f7140c9a3e2f48d33a8032090) as a separate sequence "above" the audio code stream
- During sections where audio is being modeled, text stream 0 predicts the first semantic token index $n$ of the 8 Mimi residual codes as special token `<|semantic:n|>`
- For audio, "semantic" (neural, there's not a strong distinction between) codes (from Mimi) padded with 0s during text sections

It's possible this tokenization strategy can be improved, e.g. in [Defossez et al. 2024](https://arxiv.org/html/2410.00037v2#S3.SS4.SSS4) with the base transformer predicting the Whisper-timestamped word timings as an "inner monologue" and a delay between codebook timesteps. lol i'll do it later

In [18]:
from datasets import load_dataset, DatasetDict, concatenate_datasets, load_from_disk

# If creating the libritts dataset for the first time
# from datasets import load_from_disk 
dataset = load_from_disk("../../datasets/encoded_libritts")
# train_clean_100 = load_from_disk("encoded_libritts/train.clean.100/")
# train_clean_360 = load_from_disk("encoded_libritts/train.clean.360/")
# dev_clean = load_from_disk("encoded_libritts/dev.clean")
# test_clean = load_from_disk("encoded_libritts/test.clean")
# full_train = concatenate_datasets([train_clean_100, train_clean_360])
# dataset = load_dataset("jkeisling/libritts-r-mimi-kokoro")
full_train = concatenate_datasets([dataset["train.clean.100"], dataset["train.clean.360"]])

dataset = DatasetDict({
    "train": full_train,
    "val": dataset["dev.clean"],
    "test": dataset["test.clean"]
})
dataset = dataset.with_format("torch")
dataset = dataset.remove_columns(["chapter_id", "text_original"])
dataset = dataset.rename_column(original_column_name="text_normalized", new_column_name="normalized_text")

**NOTE! This is PATH DEPENDENT on ADDING THE SEMANTIC TOKENS TO THE TOKENIZER EARLIER using `create_bytelevel_init.ipynb`. DO NOT SKIP THIS STEP OR THE MODEL WILL BE IRRETRIEVABLY BROKEN! YOU HAVE BEEN WARNED.**

==**THIS IS BYTE LEVEL!**==

In [19]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("../../inits/smoltts_byte")
tokenizer.use_default_system_prompt = False

Check this carefully: for byte level, it should be 256.

In [20]:
len(tokenizer), tokenizer.vocab_size

(2368, 256)

Please manually verify the text is done correctly. However, DECODE will not work.

In [21]:
# Test the tokenizer by encoding and decoding some example text
example_text = "This is a test sentence."
encoded = tokenizer(example_text, return_tensors="pt")
decoded = tokenizer.decode(encoded['input_ids'][0])

# Print the results
decoded

'This is a test sentence.'

In [22]:
tokenizer.encode("a, b")

[97, 44, 32, 98]

In [23]:
sequence = tokenizer.apply_chat_template([{"role": "user", "content": "help me i am trapped in this computer"}], add_generation_prompt=True,  return_tensors="pt")
sequence

tensor([[265, 257,  10, 104, 101, 108, 112,  32, 109, 101,  32, 105,  32,  97,
         109,  32, 116, 114,  97, 112, 112, 101, 100,  32, 105, 110,  32, 116,
         104, 105, 115,  32,  99, 111, 109, 112, 117, 116, 101, 114, 266,  10,
         265, 258,  10]])

In [24]:
tokenizer.decode(sequence[0, :])

'<|im_start|>user\nhelp me i am trapped in this computer<|im_end|>\n<|im_start|>assistant\n'

In [25]:
import torch

def encode_text(role: str, content: str, add_generation_prompt: bool = True) -> torch.Tensor:
    # baseline = tokenizer.apply_chat_template(f"{chr(10) if ''}<|im_start|>{role}\n{content}<|im_end|>\n",)
    baseline = tokenizer.apply_chat_template(
        [{"role": role, "content": content}],
        add_generation_prompt=add_generation_prompt,
        return_tensors="pt"
    )
    zeros_mask = torch.zeros(8, baseline.size(1), dtype=baseline.dtype)
    return torch.cat([baseline, zeros_mask])

tts_sysprompt = encode_text("system", "Speak out the provided text", add_generation_prompt=False)
tokenizer.decode(tts_sysprompt[0,:])

'<|im_start|>system\nSpeak out the provided text<|im_end|>\n'

Note that this assumes you're using ChatML. if you're NOT, then there's quite a bit more to fix.

In [26]:
SEMANTIC_OFFSET = tokenizer.encode("<|semantic:0|>")[0]
# B * C+1 * 2
VQ_USER_PREFIX = encode_text(role="user", content="")[:,:-2]
TRAILING_IM_END = torch.tensor([
    tokenizer.encode("<|im_end|>") + [0] * 8,
    tokenizer.encode("\n") + [0] * 8,
]).T

def encode_vq(codes: torch.Tensor, is_assistant=True) -> torch.Tensor:
    """
    Expects C * T
    """
    if codes.ndim != 2:
        raise ValueError("Must be single batch")
    speaker_line = codes[0,:] + SEMANTIC_OFFSET
    vq_block = torch.cat([speaker_line.unsqueeze(0), codes])

    block = torch.cat([vq_block, TRAILING_IM_END], dim=1)
    return block if is_assistant else torch.cat([VQ_USER_PREFIX, block], dim=1)


out = encode_vq(dataset["test"][0]["codes"], is_assistant=True)
tokenizer.decode(out[0,:])

'<|semantic:1049|><|semantic:1268|><|semantic:549|><|semantic:1324|><|semantic:668|><|semantic:1538|><|semantic:1593|><|semantic:95|><|semantic:629|><|semantic:1281|><|semantic:1281|><|semantic:680|><|semantic:536|><|semantic:536|><|semantic:230|><|semantic:1018|><|semantic:1117|><|semantic:244|><|semantic:507|><|semantic:997|><|semantic:1399|><|semantic:640|><|semantic:1591|><|semantic:1967|><|semantic:1161|><|semantic:690|><|semantic:67|><|semantic:1772|><|semantic:830|><|semantic:1612|><|semantic:561|><|semantic:119|><|semantic:1052|><|semantic:880|><|semantic:1029|><|semantic:1532|><|semantic:1161|><|semantic:1344|><|semantic:1109|><|semantic:6|><|semantic:1001|><|semantic:382|><|semantic:596|><|semantic:99|><|semantic:1726|><|semantic:2030|><|semantic:531|><|semantic:616|><|semantic:367|><|semantic:1271|><|semantic:1868|><|semantic:978|><|semantic:729|><|semantic:396|><|semantic:1544|><|im_end|>\n'

In [27]:
from typing import Dict

# TODO: Not doing ASR for now
def tts_tokenize_row(row: Dict):
    """
    NOTE: Deliberately ignores sysprompt line for now, can be done in packing
    """
    # system_line = tts_sysprompt
    user_line = encode_text(role="user", content=row["normalized_text"], add_generation_prompt=True)
    assistant_line = encode_vq(row["codes"])
    ground_truth = torch.cat([user_line, assistant_line], dim=1)
    # Causal shift
    tokens = ground_truth[:,:-1].clone()
    labels = ground_truth[:,1:].clone()

    # Assuming user line took care of assistant prefix
    labels[1:, :user_line.size(1) - 1] = -100
    # Mask out newline
    labels[1:, -1] = -100

    return({
        "tokens": tokens,
        "labels": labels
    })
    


example_row = tts_tokenize_row(dataset["test"][0])
tokenizer.decode(example_row["labels"][0,:])

'user\nI felt it in my bones when I woke this morning that something splendid was going to turn up.<|im_end|>\n<|im_start|>assistant\n<|semantic:1049|><|semantic:1268|><|semantic:549|><|semantic:1324|><|semantic:668|><|semantic:1538|><|semantic:1593|><|semantic:95|><|semantic:629|><|semantic:1281|><|semantic:1281|><|semantic:680|><|semantic:536|><|semantic:536|><|semantic:230|><|semantic:1018|><|semantic:1117|><|semantic:244|><|semantic:507|><|semantic:997|><|semantic:1399|><|semantic:640|><|semantic:1591|><|semantic:1967|><|semantic:1161|><|semantic:690|><|semantic:67|><|semantic:1772|><|semantic:830|><|semantic:1612|><|semantic:561|><|semantic:119|><|semantic:1052|><|semantic:880|><|semantic:1029|><|semantic:1532|><|semantic:1161|><|semantic:1344|><|semantic:1109|><|semantic:6|><|semantic:1001|><|semantic:382|><|semantic:596|><|semantic:99|><|semantic:1726|><|semantic:2030|><|semantic:531|><|semantic:616|><|semantic:367|><|semantic:1271|><|semantic:1868|><|semantic:978|><|semantic:72

In [28]:
dataset["test"][3]

{'normalized_text': "It's abominable of you to ask me.",
 'speaker_id': '4446',
 'path': '/root/.cache/huggingface/datasets/downloads/extracted/b814e720279e7b81e61bdb205446cdc8f419e2b356ec9aaec0de02275dac3aba/LibriTTS_R/test-clean/4446/2275/4446_2275_000042_000004.wav',
 'id': '4446_2275_000042_000004',
 'codes': tensor([[ 995,  301, 1237,   86,  680, 1991, 1275,   22,  922, 1137,  841, 1801,
          1441, 1495,  704,  376, 1215, 1424,  640,  779,  705, 1448,  486],
         [1912, 1366,  139,   80, 1216, 1832, 1988, 1718,  926,  546,  551,   98,
          1747,  124,  221,  129, 1837, 1094,  203, 1584,  691,   91,   91],
         [ 208,  410,  905, 1360, 1420, 1919, 1982, 1899, 1542,  722, 1890,  550,
           293,  108, 1737, 1956, 1223, 1603, 1106, 1538,  946, 2016, 1400],
         [2020,  735, 1285,  295,   33,  817, 1683,  857, 1700,  451, 1671,  316,
          1845,  138,  207,  919, 1605, 1354,  808, 1568,  316, 1601,  104],
         [ 524, 1866,  536,  958, 1957,  228, 1239

In [29]:
example_row["labels"]

tensor([[ 257,   10,   73,  ..., 1864,  266,   10],
        [-100, -100, -100,  ..., 1544,    0, -100],
        [-100, -100, -100,  ..., 1700,    0, -100],
        ...,
        [-100, -100, -100,  ...,  478,    0, -100],
        [-100, -100, -100,  ..., 1978,    0, -100],
        [-100, -100, -100,  ..., 1665,    0, -100]])

In [30]:
# DO NOT INCREASE batch size
dataset = dataset.map(tts_tokenize_row, remove_columns="codes", num_proc=12)

Map (num_proc=12): 100%|██████████| 4837/4837 [00:00<00:00, 9332.18 examples/s] 


In [15]:
dataset.save_to_disk("tokenized_libritts_bytes")

Saving the dataset (1/1 shards): 100%|██████████| 4837/4837 [00:00<00:00, 74725.32 examples/s]


In [12]:
NEWLINE_SEPARATOR = torch.tensor(tokenizer.encode("\n") + [0] * 8).unsqueeze(1)

def batch_pack_sequences(examples, window_size=768, max_items=5):
   """
   Pack sequences with system prompt and metrics
   """
   packed_tokens = []
   packed_labels = []
   packed_speakers = []
   pack_lengths = []
   items_per_pack = []
   
   tokens = examples['tokens']
   labels = examples['labels']
   speakers = examples['speaker_id']
   
   # Account for system prompt in window size
   effective_window = window_size - tts_sysprompt.shape[1]
   
   for i in range(len(tokens)):
       seq_len = tokens[i].shape[1]
       
       # Start new pack
       if i == 0 or current_length + seq_len > effective_window or \
          current_speaker != speakers[i] or current_items >= max_items:
           
           # Save previous pack if it exists
           if i > 0 and current_tokens:
               packed_tokens.append(torch.cat(current_tokens, dim=1))
               packed_labels.append(torch.cat(current_labels, dim=1))
               packed_speakers.append(current_speaker)
               pack_lengths.append(current_length + tts_sysprompt.shape[1])
               items_per_pack.append(current_items)
           
           # Initialize new pack with system prompt
           current_tokens = [tts_sysprompt, tokens[i]]
           current_labels = [tts_sysprompt, labels[i]]
           current_speaker = speakers[i]
           current_length = seq_len
           current_items = 1
           continue
           
       # Add to current pack with separator
       current_tokens.extend([NEWLINE_SEPARATOR, tokens[i]])
       current_labels.extend([NEWLINE_SEPARATOR, labels[i]])
       current_length += seq_len + 1
       current_items += 1
   
   # Don't forget last pack
   if current_tokens:
       packed_tokens.append(torch.cat(current_tokens, dim=1))
       packed_labels.append(torch.cat(current_labels, dim=1))
       packed_speakers.append(current_speaker)
       pack_lengths.append(current_length + tts_sysprompt.shape[1])
       items_per_pack.append(current_items)
   
   return {
       'tokens': packed_tokens,
       'labels': packed_labels,
       'speaker_id': packed_speakers,
       'pack_length': pack_lengths,
       'items_in_pack': items_per_pack
   }

In [16]:
# Usage:
packed_dataset = dataset.map(
    lambda row: batch_pack_sequences(row, max_items=3),
    batched=True,
    remove_columns=dataset['val'].column_names,
    batch_size=1000  # Adjust based on memory constraints
)

Map: 100%|██████████| 4837/4837 [00:01<00:00, 4760.96 examples/s]


In [14]:
example_row = packed_dataset['val'][0]
tokenizer.decode(example_row["tokens"][0,:])

'<|im_start|>system\nSpeak out the provided text<|im_end|>\n<|im_start|>assistant\n<|im_start|>user\nThe weapon must still have been there.<|im_end|>\n<|im_start|>assistant\n<|semantic:1049|><|semantic:1114|><|semantic:1609|><|semantic:784|><|semantic:499|><|semantic:260|><|semantic:1011|><|semantic:8|><|semantic:1407|><|semantic:540|><|semantic:1615|><|semantic:561|><|semantic:1945|><|semantic:201|><|semantic:1324|><|semantic:668|><|semantic:376|><|semantic:1849|><|semantic:9|><|semantic:1921|><|semantic:1921|><|semantic:1683|><|semantic:228|><|semantic:897|><|semantic:1677|><|semantic:518|><|im_end|>\n<|im_start|>user\nHow quickly he disappeared!"<|im_end|>\n<|im_start|>assistant\n<|semantic:1698|><|semantic:1848|><|semantic:1021|><|semantic:414|><|semantic:972|><|semantic:1252|><|semantic:1545|><|semantic:1363|><|semantic:307|><|semantic:722|><|semantic:1169|><|semantic:170|><|semantic:1701|><|semantic:1967|><|semantic:886|><|semantic:1540|><|semantic:1540|><|semantic:1113|><|semant

In [17]:
packed_dataset.save_to_disk("tokenized_libritts_packed_3")

Saving the dataset (1/1 shards): 100%|██████████| 1649/1649 [00:00<00:00, 31396.69 examples/s]


## Appendix: Markdown

In [24]:
tokenizer.decode(example_row[0]["labels"][0,:])

'system\nSpeak out the provided text<|im_end|>\n<|im_start|>user\nI felt it in my bones when I woke this morning that something splendid was going to turn up.<|im_end|>\n<|im_start|>assistant\n<|semantic:1049|><|semantic:1268|><|semantic:549|><|semantic:1324|><|semantic:668|><|semantic:1538|><|semantic:1593|><|semantic:95|><|semantic:629|><|semantic:1281|><|semantic:1281|><|semantic:680|><|semantic:536|><|semantic:536|><|semantic:230|><|semantic:1018|><|semantic:1117|><|semantic:244|><|semantic:507|><|semantic:997|><|semantic:1399|><|semantic:640|><|semantic:1591|><|semantic:1967|><|semantic:1161|><|semantic:690|><|semantic:67|><|semantic:1772|><|semantic:830|><|semantic:1612|><|semantic:561|><|semantic:119|><|semantic:1052|><|semantic:880|><|semantic:1029|><|semantic:1532|><|semantic:1161|><|semantic:1344|><|semantic:1109|><|semantic:6|><|semantic:1001|><|semantic:382|><|semantic:596|><|semantic:99|><|semantic:1726|><|semantic:2030|><|semantic:531|><|semantic:616|><|semantic:367|><|se

In [25]:
tokenizer.decode(example_row[1]["labels"][0,:])

'system\nTranscribe the provided speech<|im_end|>\n<|im_start|>user\n<|semantic:1049|><|semantic:1268|><|semantic:549|><|semantic:1324|><|semantic:668|><|semantic:1538|><|semantic:1593|><|semantic:95|><|semantic:629|><|semantic:1281|><|semantic:1281|><|semantic:680|><|semantic:536|><|semantic:536|><|semantic:230|><|semantic:1018|><|semantic:1117|><|semantic:244|><|semantic:507|><|semantic:997|><|semantic:1399|><|semantic:640|><|semantic:1591|><|semantic:1967|><|semantic:1161|><|semantic:690|><|semantic:67|><|semantic:1772|><|semantic:830|><|semantic:1612|><|semantic:561|><|semantic:119|><|semantic:1052|><|semantic:880|><|semantic:1029|><|semantic:1532|><|semantic:1161|><|semantic:1344|><|semantic:1109|><|semantic:6|><|semantic:1001|><|semantic:382|><|semantic:596|><|semantic:99|><|semantic:1726|><|semantic:2030|><|semantic:531|><|semantic:616|><|semantic:367|><|semantic:1271|><|semantic:1868|><|semantic:978|><|semantic:729|><|semantic:396|><|semantic:1544|><|im_end|>\n<|im_start|>assis

In [21]:
example_row["tokens"][0][1,:]

tensor([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 1698, 1719,  204, 1389,  851, 1772,  186, 1307, 1895,  832,
        1633,  771,  648, 1530, 1989, 1574, 1348,  722,  144, 1945,  278, 1109,
          29,  611,   46,  622,  628, 1740,  572,  572,  345, 1989, 1676,  929,
        1776,  749,  313, 1997, 1571,  819, 1238, 1054, 1054, 1135, 1506, 1393,
         616, 1702,  993,  579,  486,  486, 2039,  148,  657,  664,  339,  339,
         588,  212, 1443,   32, 1320, 1549,  440,    8, 1407, 1722, 1650, 1615,
         798,  121,  303,  697,  837,  358, 1882,  440, 1992, 1992,  587,  178,
         178, 1627, 1530,  929, 1610, 1916,  523,  213, 1252, 1480, 1468, 1899,
         773, 2033, 2033,   83, 1146,  7

In [28]:
example_row[1]["labels"][1,:]

tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, 1049, 1268,  549, 1324,  668, 1538, 1593,   95,  629, 1281, 1281,
         680,  536,  536,  230, 1018, 1117,  244,  507,  997, 1399,  640, 1591,
        1967, 1161,  690,   67, 1772,  830, 1612,  561,  119, 1052,  880, 1029,
        1532, 1161, 1344, 1109,    6, 1001,  382,  596,   99, 1726, 2030,  531,
         616,  367, 1271, 1868,  978,  729,  396, 1544,    0, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100])

In [28]:
dataset["test"][0]

{'normalized_text': 'I felt it in my bones when I woke this morning that something splendid was going to turn up.',
 'speaker_id': '4446',
 'id': '4446_2275_000002_000009',
 'tokens': tensor([[    1,  9690,   198, 15024,   494,   578,   260,  2711,  1694,     2,
            198,     1,  4093,   198,    57,  4592,   357,   281,   957,  6542,
            645,   339, 40652,   451,  5738,   338,  1488, 33494,   436,  2045,
            288,  1607,   614,    30,     2,   198,     1,   520,  9531,   198,
          50201, 50420, 49701, 50476, 49820, 50690, 50745, 49247, 49781, 50433,
          50433, 49832, 49688, 49688, 49382, 50170, 50269, 49396, 49659, 50149,
          50551, 49792, 50743, 51119, 50313, 49842, 49219, 50924, 49982, 50764,
          49713, 49271, 50204, 50032, 50181, 50684, 50313, 50496, 50261, 49158,
          50153, 49534, 49748, 49251, 50878, 51182, 49683, 49768, 49519, 50423,
          51020, 50130, 49881, 49548, 50696],
         [    0,     0,     0,     0,     0,     0,